fle_site/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings
from radpress import urls

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('fle_site.views',
	url(r'^$', 'landingpage', name='home'),
	# url(r'^about/$', 'about', name='about'),
	# url(r'^getinvolved/$', 'involved', name='involved'),
    # url(r'^map/$', 'map', name='map'),
)

urlpatterns += patterns('',
    url(r'^blog/', include('radpress.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
) + urlpatterns

radpress/urls.py
from django.conf.urls import patterns, url
from radpress.views import (
    ArticleArchiveView, ArticleDetailView, ArticleListView, PreviewView,
    PageDetailView, SearchView, ZenModeView, ZenModeUpdateView)
from radpress.feeds import ArticleFeed

urlpatterns = patterns(
    '',

    url(r'^$',
        view=ArticleListView.as_view(),
        name='radpress-article-list'),

    url(r'^archives/$',
        view=ArticleArchiveView.as_view(),
        name='radpress-article-archive'),

    url(r'^detail/(?P<slug>[-\w]+)/$',
        view=ArticleDetailView.as_view(),
        name='radpress-article-detail'),

    url(r'^p/(?P<slug>[-\w]+)/$',
        view=PageDetailView.as_view(),
        name='radpress-page-detail'),

    url(r'^preview/$',
        view=PreviewView.as_view(),
        name='radpress-preview'),

    url(r'^search/$',
        view=SearchView.as_view(),
        name='radpress-search'),

    url(r'^zen/$',
        view=ZenModeView.as_view(),
        name='radpress-zen-mode'),

    url(r'zen/(?P<pk>\d+)/$',
        view=ZenModeUpdateView.as_view(),
        name='radpress-zen-mode-update'),

    url(r'^rss/$',
        view=ArticleFeed(),
        name='radpress-rss'),

    url(r'^rss/(?P<tags>[-/\w]+)/$',
        view=ArticleFeed(),
        name='radpress-rss')
)

radpress/models.py
import datetime
import os
from django.conf import settings
from django.db import models
from django.db.models import Count
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _
from easy_thumbnails.files import get_thumbnailer
from radpress.compat import User
from radpress.settings import MORE_TAG, DEFAULT_MARKUP
from radpress.readers import get_reader, get_markup_choices


class ThumbnailModelMixin(object):
    def get_thumbnail(self, path, size):
        thumbnailer = get_thumbnailer(path)
        thumb = thumbnailer.get_thumbnail({'size': size, 'crop': True})

        return thumb

    def get_thumbnail_tag(self, image, size=None):
        size = size or (50, 50)
        thumb = self.get_thumbnail(image.path, size)
        url = thumb.url.replace(
            '%s/' % settings.MEDIA_ROOT, settings.MEDIA_URL)
        res = '<a href="%s" target="_blank"><img src="%s" height="%s" /></a>'

        return res % (image.url, url, size[1])


class TagManager(models.Manager):
    def get_available_tags(self):
        """
        Receives list of available tags. To be available a tag, it should be
        used by any published article.
        """
        return self.annotate(Count('article')).filter(
            article__count__gt=0, article__is_published=True)


class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    objects = TagManager()

    def __unicode__(self):
        return unicode(self.name)

    def save(self, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        return super(Tag, self).save(**kwargs)


class EntryImage(ThumbnailModelMixin, models.Model):
    name = models.CharField(
        max_length=100, blank=True,
        help_text=_("A simple description about image."))
    image = models.ImageField(upload_to='radpress/entry_images/')

    class Meta:
        verbose_name = _("Image")
        verbose_name_plural = _("Images")

    def __unicode__(self):
        image_name = os.path.split(self.image.name)[1]
        return u"%s - %s" % (self.name, image_name)

    def thumbnail_tag(self):
        if not self.image:
            return ''

        return self.get_thumbnail_tag(self.image)

    thumbnail_tag.allow_tags = True
    thumbnail_tag.short_description = ''


class EntryManager(models.Manager):
    def all_published(self, **kwargs):
        return self.filter(is_published=True, **kwargs)


class Entry(models.Model):
    """
    Radpress' main model. It includes articles to show in Radpress mainpage.
    The content body is auto filled by content value after it converted to html
    from restructuredtext. And it has `is_published` to avoid viewing in blog
    list page.

    The `created_at` is set datetime information automatically when a 'new'
    blog entry saved, but `updated_at` will be updated in each save method ran.
    """
    MARKUP_CHOICES = get_markup_choices()

    title = models.CharField(max_length=500)
    markup = models.CharField(
        max_length=20, choices=MARKUP_CHOICES, default=DEFAULT_MARKUP)
    slug = models.SlugField(unique=True)
    content = models.TextField()
    content_body = models.TextField(editable=False)
    is_published = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now)

    objects = EntryManager()

    class Meta:
        abstract = True
        ordering = ('-created_at', '-updated_at')

    def __unicode__(self):
        return unicode(self.title)

    def save(self, **kwargs):
        reader = get_reader(markup=self.markup)
        content_body, metadata = reader(self.content).read()

        if not self.content_body:
            self.content_body = content_body

        if not self.slug:
            self.slug = slugify(self.title)

        if not kwargs.pop('skip_updated_at', False):
            self.updated_at = datetime.datetime.now()

        super(Entry, self).save(**kwargs)


class Article(Entry):
    author = models.ForeignKey(User, null=True, editable=False)
    cover_image = models.ForeignKey(EntryImage, blank=True, null=True)
    tags = models.ManyToManyField(
        Tag, null=True, blank=True, through='ArticleTag')

    @property
    def content_by_more(self):
        content_list = self.content_body.split(MORE_TAG, 1)
        content = content_list[0].strip()
        return content

    @models.permalink
    def get_absolute_url(self):
        return 'radpress-article-detail', [self.slug]


class ArticleTag(models.Model):
    tag = models.ForeignKey(Tag)
    article = models.ForeignKey(Article)

    def __unicode__(self):
        return u"%s - %s" % (self.tag.name, self.article)


class Page(Entry):
    @models.permalink
    def get_absolute_url(self):
        return 'radpress-page-detail', [self.slug]


class MenuManager(models.Manager):
    def get_menu_context(self):
        menus = []
        for menu in Menu.objects.filter(page__is_published=True):
            menus.append({
                'url': menu.page.get_absolute_url(),
                'title': menu.page.title
            })

        return menus


class Menu(models.Model):
    order = models.PositiveSmallIntegerField(default=3)
    page = models.ForeignKey(Page, unique=True)

    objects = MenuManager()

    class Meta:
        unique_together = ('order', 'page')

    def __unicode__(self):
        return u'%s - %s' % (self.order, self.page.title)

radpress/forms.py
from django import forms
from django.utils.translation import ugettext as _
from radpress.models import Article, EntryImage, Page, Tag
from radpress.readers import get_reader, get_reader_initial
from radpress.settings import DEFAULT_MARKUP
from radpress.templatetags.radpress_tags import radpress_zen_mode_url


class PageForm(forms.ModelForm):
    class Meta:
        model = Page


class ZenModeForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('content', 'markup')

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ZenModeForm, self).__init__(*args, **kwargs)

        markup = getattr(self.instance, 'markup', DEFAULT_MARKUP)
        content = self.fields['content']
        content.widget = forms.Textarea(attrs={'class': 'zen-mode-textarea'})
        content.initial = get_reader_initial(markup=markup)

        # if user doesn't add radpress urls to it's project, it will be empty
        # url.
        zen_mode_url = radpress_zen_mode_url(self.instance)
        if zen_mode_url:
            help_text = _("You can also edit with <a href='%s'>zen mode</a>.")
            content.help_text = help_text % zen_mode_url

    def clean_content(self):
        field = self.cleaned_data.get('content')
        reader = get_reader(markup=self.data.get('markup'))
        self.content_body, self.metadata = reader(field).read()
        slug = self.metadata.get('slug')

        if self.metadata.get('title') is None or slug is None:
            msg = _("Title or slug can not be empty.")
            raise forms.ValidationError(msg)

        if (self.instance.pk is None
                and Article.objects.filter(slug=slug).exists()):

            msg = _("Slug should be unique.")
            raise forms.ValidationError(msg)

        return field

    def save(self, **kwargs):
        title = self.metadata.get('title')
        slug = self.metadata.get('slug')
        content = self.cleaned_data.get('content')
        is_published = self.metadata.get('published')
        image_id = self.metadata.get('image', '')

        if self.instance.pk is not None:
            article = self.instance
        else:
            article = Article(author=self.user)

        article.title = title
        article.slug = slug
        article.content = content
        article.content_body = self.content_body
        article.is_published = is_published
        article.markup = self.data.get('markup')

        # update cover image if it specified
        try:
            image = EntryImage.objects.get(id=int(image_id))
        except (EntryImage.DoesNotExist, ValueError, TypeError):
            image = None
        article.cover_image = image

        # save article
        article.save()

        # reset tags
        article.articletag_set.all().delete()
        for tag_name in self.metadata.get('tags'):
            tag = Tag.objects.get_or_create(name=tag_name)[0]
            article.articletag_set.create(tag=tag)

        return article

    def save_m2m(self):
        # TODO: this method added for fixing admin form error. But why we need
        # to this method, i don't know. Please find better way to solve this
        # problem.
        pass

radpress/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.utils.decorators import method_decorator
from django.views.generic import (
    ArchiveIndexView, DetailView, FormView, ListView, TemplateView, UpdateView,
    View)
from radpress.mixins import (
    BaseViewMixin, EntryViewMixin, JSONResponseMixin, TagViewMixin,
    ZenModeViewMixin)
from radpress import settings as radpress_settings
from radpress.models import Article, EntryImage, Page
from radpress.readers import get_reader


class ArticleListView(BaseViewMixin, TagViewMixin, ListView):
    model = Article

    def get_queryset(self):
        return self.model.objects.all_published()[:radpress_settings.LIMIT]

    def get_context_data(self, **kwargs):
        data = super(ArticleListView, self).get_context_data(**kwargs)
        data.update({'by_more': True})

        return data


class ArticleDetailView(
        BaseViewMixin, TagViewMixin, EntryViewMixin, DetailView):
    model = Article


class PageDetailView(BaseViewMixin, TagViewMixin, EntryViewMixin, DetailView):
    model = Page


class ArticleArchiveView(BaseViewMixin, TagViewMixin, ArchiveIndexView):
    model = Article
    date_field = 'created_at'
    paginate_by = 25

    def get_queryset(self):
        queryset = self.model.objects.all_published()

        # filter for tags, if possible...
        tag = self.request.GET.get('tag')
        if tag:
            queryset = queryset.filter(tags__slug=tag)

        return queryset

    def get_context_data(self, **kwargs):
        data = super(ArticleArchiveView, self).get_context_data(**kwargs)
        data.update({
            'enabled_tag': self.request.GET.get('tag')
        })

        return data


class SearchView(BaseViewMixin, TemplateView):
    template_name = 'radpress/search.html'
    models = (Article, Page)

    def get_queryset(self):
        queryset = []
        q = self.request.GET.get('q')

        if not q:
            return queryset

        for model in self.models:
            queryset += model.objects.filter(
                Q(title__icontains=q) | Q(slug__icontains=q) |
                Q(content__icontains=q), is_published=True)

        return queryset

    def get_context_data(self, **kwargs):
        data = super(SearchView, self).get_context_data(**kwargs)
        data.update({'object_list': self.get_queryset()})

        return data


class PreviewView(JSONResponseMixin, View):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(PreviewView, self).dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        content = request.POST.get('content', '')
        markup = request.POST.get('markup')
        reader = get_reader(markup=markup)
        content_body, metadata = reader(content).read()
        image_id = metadata.get('image', '')
        try:
            image_url = EntryImage.objects.get(id=int(image_id)).image.url
        except (EntryImage.DoesNotExist, ValueError):
            image_url = ''

        context = {
            'content': content_body,
            'title': metadata.get('title'),
            'tags': list(metadata.get('tags', [])),
            'image_url': image_url
        }

        return self.render_to_response(context)


class ZenModeView(ZenModeViewMixin, FormView):
    pass


class ZenModeUpdateView(ZenModeViewMixin, UpdateView):
    model = Article

radpress/templates/radpress/partials/archive_list.html
{% load trans from i18n %}
{% load url from future %}


{% for object in object_list %}
  <div class="archive-item">
    <time data-datetime="{{ object.updated_at }}">{{ object.updated_at|date:"b d, Y"|upper }}</time>
    <h2 class="article-title">
      <a href="{{ object.get_absolute_url }}">{{ object.title }}</a>
    </h2>
  </div>
{% empty %}
  <p>{% trans "No entries found." %}</p>
{% endfor %}

radpress/templates/radpress/partials/disqus.html
<div id="disqus_thread"></div>

<script type="text/javascript">
var disqus_shortname = '{{ RADPRESS_DISQUS }}';
(function() {
  var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
  dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

radpress/templates/radpress/partials/entry.html
{% comment %}
Arguments:
- summary: Default, 0
{% endcomment %}

{% load blocktrans trans from i18n %}
{% load radpress_datetime from radpress_tags %}
{% load radpress_full_name from radpress_tags %}
{% load url from future %}

<div class="post-wrap">
  <div class="post type-post status-publish format-gallery hentry category-uncategorized post">
    <div class="box">
      {% if object.cover_image %}
        <div class="gallery-wrap">
          <a href="{{ object.get_absolute_url }}" title="{{ object.title }}">
            <img src="{{ object.cover_image.image.url }}" alt="{{ object.cover_image.name }}" />
          </a>
        </div>
        <div class="clear"></div>
      {% endif %}

      <div class="frame">
        <div class="title-wrap">
          {% if user == object.author %}
            <a href="{% url 'radpress-zen-mode-update' object.pk %}" class="edit-button">{% trans "Edit" %}</a>
          {% endif %}
          <h2 class="entry-title">
            <a href="{{ object.get_absolute_url }}" title="{{ object.title }}">{{ object.title }}</a>
          </h2>
          <div class="title-meta">
            <span>{{ object.author|radpress_full_name }}</span>
            <span>{% radpress_datetime object.updated_at %}</span>
          </div>
        </div>
        <div class="post-content">
          {% if summary %}
            {{ object.content_by_more|safe }}
            <p>
              <a class="more-link" href="{{ object.get_absolute_url }}">{% trans "Read more" %} →</a>
            </p>
          {% else %}
            {{ object.content_body|safe }}
          {% endif %}
        </div>
        <div class="bar">
          <div class="bar-frame clearfix">
            <div class="meta-info">
              {% if object.tags.count %}
                <div class="tags">
                  {% for tag in object.tags.all %}
                    <a rel="tag" title="{% blocktrans %}View all posts in {{ tag.name }}{% endblocktrans %}" href="{% url 'radpress-article-archive' %}?tag={{ tag.slug }}">{{ tag.name }}</a>
                  {% endfor %}
                </div>
              {% endif %}
              <div class="share">
                {% include "radpress/partials/share.html" %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

radpress/templates/radpress/partials/ga_code.html
<script>
  var _gaq=[['_setAccount','{{ RADPRESS_GA_CODE }}'],['_trackPageview']];
  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
  g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
  s.parentNode.insertBefore(g,s)}(document,'script'));
</script>

radpress/templates/radpress/partials/navigation.html
{% load trans from i18n %}

{% if page_obj %}
  <div class="post-nav">
    {% if page_obj.has_previous %}
      <div class="postnav-left">
        <a href="?{% if enabled_tag %}tag={{ enabled_tag }}{% endif %}&page={{ page_obj.previous_page_number }}">&larr; {% trans "previous" %}</a>
      </div>
    {% endif %}

    {% if page_obj.has_next %}
      <div class="postnav-right">
        <a href="?{% if enabled_tag %}tag={{ enabled_tag }}{% endif %}&page={{ page_obj.next_page_number }}">{% trans "next" %} &rarr;</a>
      </div>
    {% endif %}
  </div>
{% endif %}

radpress/templates/radpress/partials/search_form.html
{% load trans from i18n %}
{% load url from future %}

<form class="search-form clearfix" action="{% url 'radpress-search' %}" method="GET">
  <fieldset>
    <input class="submit" type="submit" value="{% trans "Go" %}" />
    <input type="text"
           class="search-form-input text"
           value="{% trans "Search" %}"
           onblur="if (this.value == '') {this.value = '{% trans "Search" %}';}"
           onfocus="if (this.value == '{% trans "Search" %}') {this.value = '';}"
           name="q" />
  </fieldset>
</form>

radpress/templates/radpress/partials/share.html
{% load radpress_get_url from radpress_tags %}
{% radpress_get_url object as url %}

{% with title=object.title %}
  {# google plus #}
  <a class="share-google" href="https://plus.google.com/share?url={{ url }}" title="{{ title }}" target="blank">google</a>

  {# facebook #}
  <a class="share-facebook" href="http://www.facebook.com/share.php?u={{ url }}" title="{{ title }}" target="blank">facebook</a>

  {# twitter #}
  <a class="share-twitter" href="http://twitter.com/home?status={{ title }} - {{ url }}" title="{{ title }}" target="blank">twitter</a>
{% endwith %}

radpress/templates/radpress/partials/tag_cloud.html
{% load url from future %}

<div class="sidebar-box">
  <div class="tagcloud">
    {% for tag in tag_list %}
      <a class="label {% if tag.slug != enabled_tag %} label-info{% endif %}"
         href="{% url 'radpress-article-archive' %}?tag={{ tag.slug }}">
        <i class="icon-tag icon-white"></i>
        {{ tag.name }}
      </a>
    {% endfor %}
  </div>
</div>